### ISSUE TITLE
Method "$model->getDetailUrl()" is deprectaed, use "$model->detailLink" instead.

### ISSUE THREAD

**Issue by Saraylu** [luyadev/luya-module-gallery#2]
I get this message:
`Method "$model->getDetailUrl()" is deprectaed, use "$model->detailLink" instead.`
Know you what is the reason?

**Comment by nadar** [comment]
Because we changed the name as you can read in the message. Or whats exactly your question? :-)

**Comment by Saraylu** [comment]
I installed the module according  to guide.
Create an album and added `Gallery:Album` to a page.
Now i get the error!

**Comment by nadar** [comment]
I have replaced the deprecated method in the view file, i hope it works now out of the box (install dev-master in order to test) or override the view files in your project.

**Comment by Saraylu** [comment]
I have commented on the [commit ](https://github.com/luyadev/luya-module-gallery/commit/25a4bd7366c1d1b62a31ab38e2bd968833baf03e#diff-d60c109c929122a2e3e6fa29a5c44601) about getter and setter method.

Issue solved. Thanks for quick answer :)

Please commit on master branch to available in composer

**Comment by Saraylu** [comment]
`views/gallery/album/index.php` also have use deprecated method

**Comment by nadar** [comment]
done. Its available trough composer, sometimes it can take some time (caching)
