### ISSUE TITLE
Obtain image URL

### ISSUE THREAD

**Issue by Saraylu** [luyadev/luya-module-gallery#4]
The sample code in README `<?= $image->source; ?>` **source** is a unknown property !
How can obtain image url ? (`Yii::$app->storage->fileAbsoluteHttpPath($fileName);`)
I'm reading the code to obtain the solution, but if you know thanks to share it :)
```
<table border="1">
    <tr>
        <td>
            <h2><?= $model->title; ?></h2>
            <p><?= $model->description; ?></p>
            <p><a href="<?= $model->detailLink; ?>"><?= $model->detailLink; ?></a>

            <h3>Bilder</h3>
            <div class="row">
                <?php foreach($model->albumImages as $image): ?>
                    <div class="col-md-3">
                        <img class="img-responsive" src="<?= $image->source; ?>" border="0" />
                    </div>
                <?php endforeach; ?>
            </div>
        </td>
    </tr>
</table>
```

**Comment by Saraylu** [comment]
I find solution for this sample code:
`<?= $image->getImage()->source; ?>`
Do is better way?

**Comment by nadar** [comment]
Thanks for taking care of this. Yes this is correctly. We had to restructure the module, and we have not changed the readme and view files accordingly, sorry for that. So we can close the issue?
